# Generated by Django 6.0.3 on 2026-04-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_collaborationteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_team',
            field=models.ForeignKey(blank=True, help_text='Current collaboration team context', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='user.collaborationteam'),
        ),
    ]
