# Generated by Django 6.0.3 on 2026-04-04 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_active_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationTeamInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_team_invitations",
                        to="user.user",
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_invitations",
                        to="user.user",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="user.collaborationteam",
                    ),
                ),
            ],
            options={
                "db_table": "collaboration_team_invitation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="collaborationteaminvitation",
            index=models.Index(
                fields=["invited_user", "status"],
                name="collaboratio_invited_6d621a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationteaminvitation",
            index=models.Index(
                fields=["team", "invited_user", "status"],
                name="collaboratio_team_id_0624e8_idx",
            ),
        ),
    ]
