# Generated by Django 6.0.3 on 2026-04-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_collaborationteaminvitation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="collaborationteaminvitation",
            new_name="collaborati_invited_a2b039_idx",
            old_name="collaboratio_invited_6d621a_idx",
        ),
        migrations.RenameIndex(
            model_name="collaborationteaminvitation",
            new_name="collaborati_team_id_97f404_idx",
            old_name="collaboratio_team_id_0624e8_idx",
        ),
    ]
