# Generated by Django 6.0.3 on 2026-04-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_remove_user_role"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="user_role_3744fd_idx",
        ),
    ]
