# Generated by Django 5.2.8 on 2026-04-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_user_user_role_3744fd_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDataExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("rate_limited", "Rate limited"),
                            ("error", "Error"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_export_logs",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_data_export_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userdataexportlog",
            index=models.Index(
                fields=["user", "created_at"],
                name="user_data_ex_user_id_2fc8a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userdataexportlog",
            index=models.Index(
                fields=["outcome", "created_at"],
                name="user_data_ex_outcome_3fb3cb_idx",
            ),
        ),
    ]
