# Generated by Django 6.0.3 on 2026-04-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_userdataexportlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userdataexportlog",
            new_name="user_data_e_user_id_d43bf6_idx",
            old_name="user_data_ex_user_id_2fc8a9_idx",
        ),
        migrations.RenameIndex(
            model_name="userdataexportlog",
            new_name="user_data_e_outcome_e50679_idx",
            old_name="user_data_ex_outcome_3fb3cb_idx",
        ),
    ]
