# Generated by Django 5.2.8 on 2026-04-11

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_rename_user_data_ex_user_id_2fc8a9_idx_user_data_e_user_id_d43bf6_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True,
                help_text=_("User password hash or NULL after irreversible account deletion"),
                max_length=128,
                null=True,
                verbose_name=_("password"),
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text=_("Permanent account deletion timestamp"),
                null=True,
            ),
        ),
    ]
