# Generated by Django 6.0.3 on 2026-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_remove_userdataexportlog_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborationteam",
            name="schedule_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-stage timetable configuration. Keys are stage codes (PRESCHOOL/PRIMARY/SECONDARY/ALEVELS); values are objects with start_time, end_time, break_start, break_end, session_duration.",
            ),
        ),
    ]
