# Generated by Django 6.0.3 on 2026-04-10 00:00

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Incident timestamp.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Incident details: reason, scope, action taken.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User affected by the incident; NULL if user was deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_incident",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["user", "created_at"],
                name="sec_incident_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["created_at"],
                name="sec_incident_created_idx",
            ),
        ),
    ]
