# Generated by Django 6.0.3 on 2026-03-22 19:25

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0002_classroom_classroom_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="classroom_name_ci_unique",
            ),
        ),
    ]
