# Generated by Django 6.0.3 on 2026-03-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_remove_classroom_classroom_type_classroom_home_group_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classroom',
            name='classroom_shared_home_group_consistency',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='home_group',
        ),
    ]
