# Generated by Django 6.0.3 on 2026-05-04 17:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0006_classroom_team"),
        ("user", "0015_collaborationteam_schedule_config"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classroom",
            name="classroom_name_ci_unique",
        ),
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                models.F("team"),
                django.db.models.functions.text.Lower("name"),
                name="classroom_team_name_ci_unique",
            ),
        ),
    ]
