# Generated by Django 6.0.2 on 2026-03-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("updated_by", models.CharField(blank=True, max_length=150)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("preschool", "Preschool"),
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "group",
                "ordering": ["name", "id"],
            },
        ),
    ]
