# Generated by Django 6.0.3 on 2026-03-22 19:25

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="group_name_ci_unique",
            ),
        ),
    ]
