# Generated by Django 6.0.3 on 2026-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0003_group_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="stage",
            field=models.CharField(
                choices=[
                    ("preschool", "Infantil"),
                    ("primary", "Primaria"),
                    ("secondary", "ESO"),
                    ("alevels", "Bachillerato"),
                ],
                max_length=20,
            ),
        ),
    ]
