# Generated by Django 6.0.3 on 2026-04-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0004_alter_group_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="stage",
            field=models.CharField(max_length=50),
        ),
    ]
