# Generated by Django 6.0.2 on 2026-03-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teacher", "0002_ensure_teacher_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("updated_by", models.CharField(blank=True, max_length=150)),
                ("weekly_hours", models.PositiveIntegerField()),
                ("duration", models.FloatField()),
                ("preferred_time_slot", models.CharField(blank=True, max_length=150)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PRESCHOOL", "Preschool"),
                            ("PRIMARY", "Primary"),
                            ("SECONDARY", "Secondary"),
                        ],
                        default="PRIMARY",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("TC", "TC")],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="teacher.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "subject",
                "ordering": ["name", "id"],
            },
        ),
    ]
