# Generated by Django 6.0.3 on 2026-03-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0003_subject_time_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="required_classroom_type",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
