# Generated by Django 6.0.3 on 2026-03-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0004_subject_required_classroom_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="duration",
            field=models.FloatField(default=1.0),
        ),
    ]
