# Generated by Django 6.0.3 on 2026-03-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_subject_subject_name_ci_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='required_classroom_type',
        ),
    ]
