# Generated by Django 6.0.3 on 2026-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0009_subject_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="stage",
            field=models.CharField(
                choices=[
                    ("PRESCHOOL", "Infantil"),
                    ("PRIMARY", "Primaria"),
                    ("SECONDARY", "ESO"),
                    ("ALEVELS", "Bachillerato"),
                ],
                default="PRIMARY",
                max_length=20,
            ),
        ),
    ]
