# Generated by Django 6.0.3 on 2026-04-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0010_alter_subject_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="stage",
            field=models.CharField(default="PRIMARY", max_length=50),
        ),
    ]
