# Generated by Django 6.0.3 on 2026-05-04 17:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0007_remove_classroom_classroom_name_ci_unique_and_more"),
        ("group", "0007_remove_group_group_name_ci_unique_and_more"),
        ("subject", "0011_alter_subject_stage"),
        ("teacher", "0007_alter_teacher_team"),
        ("user", "0015_collaborationteam_schedule_config"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subject",
            name="subject_name_ci_unique",
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                models.F("team"),
                django.db.models.functions.text.Lower("name"),
                name="subject_team_name_ci_unique",
            ),
        ),
    ]
