# Generated by Django 6.0.3 on 2026-05-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0013_subject_mandatory_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="stage",
        ),
    ]
