# Generated by Django 6.0.3 on 2026-05-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0015_delete_tc_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="type",
            field=models.CharField(
                choices=[("NORMAL", "Normal")], default="NORMAL", max_length=20
            ),
        ),
    ]
