# Generated by Django 6.0.5 on 2026-05-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0016_alter_subject_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="preferred_time_slot",
        ),
    ]
