# Generated by Django 6.0.3 on 2026-03-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auditableEntity", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditentry",
            new_name="audit_entry_entity__202b83_idx",
            old_name="audit_entry_entity__f62798_idx",
        ),
        migrations.RenameIndex(
            model_name="auditentry",
            new_name="audit_entry_action__54a4e1_idx",
            old_name="audit_entry_action__a0cb4f_idx",
        ),
        migrations.RenameIndex(
            model_name="auditentry",
            new_name="audit_entry_actor_e_270ac8_idx",
            old_name="audit_entry_actor_e_2d9498_idx",
        ),
        migrations.RenameIndex(
            model_name="auditentry",
            new_name="audit_entry_occurre_d942b7_idx",
            old_name="audit_entry_occurre_d7e0ca_idx",
        ),
    ]
