# Generated by Django 6.0.3 on 2026-04-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditableEntity", "0002_auditentry_actor_name_and_security_refactor"),
        ("user", "0007_collaborationteaminvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditentry",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_entries",
                to="user.collaborationteam",
            ),
        ),
        migrations.AddIndex(
            model_name="auditentry",
            index=models.Index(
                fields=["team", "occurred_at"],
                name="audit_entry_team_oc_f2a670_idx",
            ),
        ),
    ]
