# Generated by Django 6.0.2 on 2026-03-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
