# Generated by Django 6.0.2 on 2026-03-07 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_schedule_name"),
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="subject.subject",
            ),
        ),
    ]
