# Generated by Django 6.0.3 on 2026-03-22 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0003_classroom_classroom_name_ci_unique"),
        ("group", "0002_group_group_name_ci_unique"),
        ("schedule", "0003_schedule_subject"),
        ("subject", "0006_subject_subject_name_ci_unique"),
        ("teacher", "0005_teacher_teacher_name_ci_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="schedule_end_after_start",
            ),
        ),
    ]
