# Generated by Django 6.0.3 on 2026-04-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_scheduledefect"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scheduledefect",
            name="unique_schedule_defect",
        ),
        migrations.RenameIndex(
            model_name="scheduledefect",
            new_name="schedule_de_schedul_e7c351_idx",
            old_name="schedule_de_schedule_defect_code_idx",
        ),
        migrations.RenameIndex(
            model_name="scheduledefect",
            new_name="schedule_de_entity__bfefb7_idx",
            old_name="schedule_de_entity_type_entity_id_idx",
        ),
        migrations.AlterUniqueTogether(
            name="scheduledefect",
            unique_together={("schedule", "defect_code", "entity_id")},
        ),
    ]
