# Generated by Django 6.0.3 on 2026-04-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_remove_scheduledefect_unique_schedule_defect_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scheduledefect",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="scheduledefect",
            name="schedule_de_schedul_e7c351_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduledefect",
            name="schedule_de_entity__bfefb7_idx",
        ),
        migrations.DeleteModel(
            name="ScheduleDefect",
        ),
    ]
