# Generated by Django 6.0.3 on 2026-05-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0006_classroom_team"),
        ("group", "0006_uppercase_group_stages"),
        ("schedule", "0008_alter_scheduledefect_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="classroom.classroom",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="group.group",
            ),
        ),
    ]
