# Generated by Django 6.0.3 on 2026-05-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0009_nullable_classroom_group_for_tc"),
        ("teacher", "0009_teacher_max_weekly_minutes_and_more"),
        ("user", "0015_collaborationteam_schedule_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="TCSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.SmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc_sessions",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="user.collaborationteam",
                    ),
                ),
            ],
            options={
                "db_table": "tc_session",
                "ordering": ["day", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "day"], name="tc_session_teacher_01197b_idx"
                    ),
                    models.Index(
                        fields=["team", "day"], name="tc_session_team_id_49f315_idx"
                    ),
                ],
            },
        ),
    ]
