# Generated by Django 6.0.3 on 2026-05-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0011_tcsession_add_timetable_name"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tcsession",
            new_name="tc_session_team_id_d60d72_idx",
            old_name="tc_session_team_id_obs_idx",
        ),
    ]
