# Generated by Django 6.0.3 on 2026-05-14 16:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "schedule",
            "0012_rename_tc_session_team_id_obs_idx_tc_session_team_id_d60d72_idx",
        ),
        ("user", "0015_collaborationteam_schedule_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("DONE", "Done"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("generation_options", models.JSONField(default=dict)),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("error_data", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="user.collaborationteam",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_generation_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "created_by", "status"],
                        name="schedule_ge_team_id_878d4c_idx",
                    )
                ],
            },
        ),
    ]
