# Generated by Django 6.0.5 on 2026-05-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0013_schedule_generation_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulegenerationjob",
            name="current_phase",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
