# Generated by Django 6.0.3 on 2026-03-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_time_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='unavailability',
        ),
    ]
