# Generated by Django 6.0.3 on 2026-03-22 19:25

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_availability_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='teacher_name_ci_unique'),
        ),
    ]
