# Generated by Django 6.0.3 on 2026-04-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacher_team'),
        ('user', '0006_alter_user_active_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='user.collaborationteam'),
        ),
    ]
