# Generated by Django 6.0.3 on 2026-05-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0008_remove_teacher_teacher_name_ci_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="max_weekly_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teacher",
            name="weekly_hours_exact",
            field=models.BooleanField(default=False),
        ),
    ]
